import os
import tempfile
import shutil
import requests
import time
from git import Repo

def create_pull_request(
    repo_state,
    patch_set,
    repo_key,
    base_branch="main"
):
    """
    Creates a PR by cloning the repo, applying modified files from repo_state, committing the changes, pushing a new branch, and opening a PR.
    """
    
    print("inside create pull request")
    
    token = os.getenv('GITHUB_WRITE_TOKEN')
    
    if not token:
        raise RuntimeError("GITHUB_WRITE_TOKEN not set")
    
    repo_url = f"https://{token}@github.com/{repo_key}"
    temp_dir = tempfile.mkdtemp(prefix="ai_patch_repo_")

    try:
        repo = Repo.clone_from(repo_url, temp_dir)
        repo.git.clear_cache()

        # branch creation
        branch_name = f"ai-fix-{os.urandom(4).hex()}"

        repo.git.checkout("-b", branch_name)

        changed_files = { p.file for p in patch_set.patches }
        
        for path in changed_files:
            abs_path = os.path.join(temp_dir,path)

            if path not in repo_state:
                raise RuntimeError(f"{path} missing from repo_state")
            
            os.makedirs(os.path.dirname(abs_path), exist_ok=True)

            with open(abs_path, "w", encoding="utf-8") as f:
                f.write("\n".join(repo_state[path]))
        
        # stage only modified files
        repo.git.add(*changed_files)

        if not repo.is_dirty():
            raise RuntimeError("No changes detected")
        
        # commit
        repo.index.commit("fix: automated patch generated by RepoPilot")

        # push branch
        repo.git.push("--set-upstream", "origin", branch_name)

        # create PR via github API
        url = f"https://api.github.com/repos/{repo_key}/pulls"

        payload = {
            "title": "AI generated fix",
            "body": "This pull request was automatically generated by the AI patch agent.",
            "head": branch_name,
            "base": base_branch
        }

        headers = {
            "Authorization": f"Bearer {token}",
            "Accept": "application/vnd.github+json"
        }

        response = requests.post(url, json=payload, headers=headers)

        if response.status_code != 201:
            raise RuntimeError(response.text)
        
        return response.json()['html_url']
    
    finally:
        try:
            repo.close()
        except:
            pass

        for _ in range(5):
            try:
                shutil.rmtree(temp_dir)
                break
            except PermissionError:
                time.sleep(0.5)